module.exports = {
    "022":"Acuamanala de Miguel Hidalgo",
    "001":"Amaxac de Guerrero",
    "002":"Apetatitlán de Antonio Carvajal",
    "005":"Apizaco",
    "003":"Atlangatepec",
    "004":"Atltzayanca",
    "045":"Benito Juárez",
    "006":"Calpulalpan",
    "010":"Chiautempan",
    "018":"Contla de Juan Cuamatzi",
    "008":"Cuapiaxtla",
    "009":"Cuaxomulco",
    "007":"El Carmen Tequexquitla",
    "046":"Emiliano Zapata",
    "012":"Españita",
    "013":"Huamantla",
    "014":"Hueyotlipan",
    "015":"Ixtacuixtla de Mariano Matamoros",
    "016":"Ixtenco",
    "048":"La Magdalena Tlaltelulco",
    "047":"Lázaro Cárdenas",
    "017":"Mazatecochco de José María Morelos",
    "011":"Muñoz de Domingo Arenas",
    "021":"Nanacamilpa de Mariano Arista",
    "023":"Natívitas",
    "024":"Panotla",
    "041":"Papalotla de Xicohténcatl",
    "049":"San Damián Texóloc",
    "050":"San Francisco Tetlanohcan",
    "051":"San Jerónimo Zacualpan",
    "052":"San José Teacalco",
    "053":"San Juan Huactzinco",
    "054":"San Lorenzo Axocomanitla",
    "055":"San Lucas Tecopilco",
    "025":"San Pablo del Monte",
    "020":"Sanctórum de Lázaro Cárdenas",
    "056":"Santa Ana Nopalucan",
    "057":"Santa Apolonia Teacalco",
    "058":"Santa Catarina Ayometla",
    "059":"Santa Cruz Quilehtla",
    "026":"Santa Cruz Tlaxcala",
    "060":"Santa Isabel Xiloxoxtla",
    "027":"Tenancingo",
    "028":"Teolocholco",
    "019":"Tepetitla de Lardizábal",
    "029":"Tepeyanco",
    "030":"Terrenate",
    "031":"Tetla de la Solidaridad",
    "032":"Tetlatlahuca",
    "033":"Tlaxcala",
    "034":"Tlaxco",
    "035":"Tocatlán",
    "036":"Totolac",
    "038":"Tzompantepec",
    "039":"Xaloztoc",
    "040":"Xaltocan",
    "042":"Xicohtzinco",
    "043":"Yauhquemehcan",
    "044":"Zacatelco",
    "037":"Ziltlaltépec de Trinidad Sánchez Santos"
}